export const docs = [
  {
    id: 'remote-access',
    label: 'Acesso remoto',
    eyebrow: 'Recomendação',
    title: 'Portal estático publicado por CI',
    summary:
      'O OpenJira Docs deve ser um site estático versionado, publicado automaticamente em GitHub Pages via GitHub Actions.',
    items: [
      'Projeto dedicado: openjira-docs, independente do frontend e do backend.',
      'Deploy selecionado: GitHub Pages com GitHub Actions publicando a pasta dist.',
      'Cloudflare Pages fica como alternativa futura para domínio customizado e previews avançados.',
      'Conteúdo versionado junto ao código para manter histórico de decisões, sprints e relatórios.',
      'Sem dependência de banco ou servidor para leitura dos documentos.',
    ],
  },
  {
    id: 'agency-governance',
    label: 'Governança AIA',
    eyebrow: 'Operating model',
    title: 'Squad autônoma com workflow obrigatório',
    summary:
      'A AIA opera de forma independente, mas todo trabalho deve passar pelo fluxo de backlog, card, desenvolvimento, teste, QA, review e documentação.',
    items: [
      'Gestão: Mariana, TechLead e Analista de Requisitos definem e validam backlog item por item.',
      'Mariana cria épicos e cards completos, com requisitos, dependências, critérios, evidências e links de KB.',
      'TechLead revisa cards, atribui conforme especialidade e senioridade, faz code review final e decide PR.',
      'Developers implementam, testam, criam testes, commitam e notificam tester.',
      'Tester e QA nunca corrigem código; retornam cards com evidências, tags e prioridade quando falhar.',
      'Documentarista atualiza Markdown e usa Mermaid quando o fluxo, arquitetura ou decisão exigir clareza visual.',
    ],
  },
  {
    id: 'delivery-workflow',
    label: 'Workflow',
    eyebrow: 'Lei operacional',
    title: 'Fluxo obrigatório antes de qualquer execução',
    summary:
      'Nenhum membro trabalha fora do próprio escopo. Cada card precisa passar pelo ciclo formal de gestão, desenvolvimento, qualidade, review e documentação.',
    items: [
      'Documento fonte: docs/operations/aia-delivery-workflow.md.',
      'Management team: PM Mariana, TechLead e Analista de Requisitos.',
      'A Mariana solicita acessos por meio da equipe de infra.',
      'Cards retornados por tester, QA ou TechLead tem prioridade sobre novas tasks, sempre pelo mais antigo.',
      'Tags obrigatórias para retorno: URGENTE, BUG, TESTER, QA, SONARQUBE, CODE_REVIEW e DEBITO_TECNICO.',
    ],
  },
  {
    id: 'product-vision',
    label: 'Visão',
    eyebrow: 'Produto',
    title: 'OpenJira como ferramenta de gestão de trabalho',
    summary:
      'O OpenJira é uma ferramenta web para times de produto, engenharia e operações organizarem projetos, tarefas, prioridades e entregas.',
    items: [
      'Foco em Kanban e Scrum para times pequenos e médios.',
      'Experiência densa, clara e adequada ao uso recorrente.',
      'Backend próprio em NestJS com PostgreSQL.',
      'Frontend próprio em Next.js.',
      'APIs documentadas para automação e integrações futuras.',
    ],
  },
  {
    id: 'mvp',
    label: 'MVP',
    eyebrow: 'Escopo',
    title: 'Validar um projeto real do início ao fim',
    summary:
      'O MVP deve provar que um time consegue autenticar, criar projetos, gerir issues e acompanhar o fluxo pelo board.',
    items: [
      'Autenticação de usuários.',
      'Organizações, membros e projetos.',
      'Board Kanban por projeto.',
      'Issues com tipo, prioridade, responsável, status e comentários.',
      'Drag and drop entre colunas.',
      'Histórico básico de mudanças e filtros essenciais.',
    ],
  },
  {
    id: 'sprints',
    label: 'Sprints',
    eyebrow: 'Execução',
    title: 'Cadência autônoma com gate de TechLead',
    summary:
      'As sprints são planejadas pela AIA, mas cards de implementação só entram em execução depois de card completo, dependências explícitas e TechLead review.',
    items: [
      'Sprint 000: fundação, workflow AIA, backlog completo, docs, arquitetura, dados, qualidade e CI/CD baseline.',
      'Sprint 001: autenticação, RBAC, organizações, projetos, banco inicial e app shell.',
      'Sprint 002: board Kanban, colunas, movimentação transacional, rotas Next.js e UI do board.',
      'Sprint 003: issues, comentários, histórico, filtros, acessibilidade e testes E2E MVP.',
      'Sprint 004: hardening, SonarQube, required checks, deploy, rollback, evidências e release readiness.',
    ],
  },
  {
    id: 'quality-gates',
    label: 'Quality gates',
    eyebrow: 'Qualidade',
    title: 'Quality gates aprovados na Sprint 000',
    summary:
      'A política de qualidade foi aprovada na Sprint 000 e o workflow exige validação objetiva antes de considerar uma entrega pronta.',
    items: [
      'Card fonte: OJ-019 - Define quality gates.',
      'Critérios candidatos: lint, formatação, typecheck e build aprovados.',
      'Testes unitários e integração para áreas alteradas entram na política.',
      'Fluxos críticos devem ser cobertos por E2E quando houver interface pronta.',
      'SonarQube e required checks dependem dos cards OJ-022 e OJ-024.',
      'Documentação deve ser atualizada quando houver mudança funcional, técnica ou operacional.',
    ],
  },
  {
    id: 'task-board',
    label: 'Tasks',
    eyebrow: 'Backlog',
    title: 'Backlog MVP e Sprint 000 concluídos',
    summary:
      'A AIA reestruturou o backlog usando o card model obrigatório. A SPR-000 foi concluída e deixou a fundação pronta para o planejamento da Sprint 001.',
    items: [
      'Backlog: docs/product/mvp-backlog.md.',
      'Sprint ativa: docs/sprints/sprint-000-plan.md.',
      'Roadmap: docs/sprints/sprint-001-plan.md até docs/sprints/sprint-004-plan.md.',
      'Template de relatório: docs/sprints/report-template.md.',
      'Status atual: Sprint-000 concluída; fundação aprovada para planejamento da Sprint 001.',
      'Próximo foco autônomo: planejar Sprint 001 e agendar OJ-021 quando necessário.',
    ],
  },
]

export const agents = [
  'Mariana Costa - Product Strategy',
  'Helena Duarte - Requisitos',
  'Rafael Almeida - Tech Lead',
  'Beatriz Nogueira - UX/UI',
  'Lucas Ferreira - Frontend Next.js',
  'Gabriel Martins - Backend NestJS',
  'Eduardo Ribeiro - DBA PostgreSQL',
  'Camila Rocha - CI/CD',
  'Bruno Teixeira - Testes Integração/E2E/P2P',
  'Renata Barbosa - Quality Gate/QA',
  'Sofia Mendes - Documentação',
]

export const sprintStatus = {
  id: 'SPR-001',
  name: 'Identity, Access And Project Foundation',
  state: 'active',
  startedAt: '2026-07-05',
  reportCadence: 'Relatório ao fim da sprint',
}

export const sprintRoadmap = [
  {
    id: 'SPR-000',
    title: 'Foundation And Operating Model',
    state: 'done',
    goal: 'Fechou workflow, backlog, docs, arquitetura, dados, qualidade e CI/CD baseline.',
    cards: ['OJ-001', 'OJ-002R', 'OJ-003', 'OJ-004', 'OJ-005', 'OJ-006', 'OJ-007', 'OJ-008', 'OJ-009', 'OJ-010', 'OJ-011', 'OJ-012', 'OJ-BE-001', 'OJ-013', 'OJ-014', 'OJ-015', 'OJ-019', 'OJ-020', 'OJ-023', 'OJ-026'],
  },
  {
    id: 'SPR-001',
    title: 'Identity, Access And Project Foundation',
    state: 'active',
    goal: 'Entregar base de autenticação, RBAC, organizações, projetos, banco inicial e shell autenticado.',
    cards: ['OJ-DB-001', 'OJ-DB-002', 'OJ-DB-003', 'OJ-016', 'OJ-BE-002', 'OJ-AUTH-001', 'OJ-AUTH-002', 'OJ-BE-003', 'OJ-017', 'OJ-FE-001', 'OJ-FE-002', 'OJ-FE-003'],
  },
  {
    id: 'SPR-002',
    title: 'Kanban Board And Issue Movement',
    state: 'planned',
    goal: 'Entregar board Kanban com colunas, cards, movimentação, API de board e UI responsiva.',
    cards: ['OJ-BE-004', 'OJ-018', 'OJ-FE-004', 'OJ-UX-001'],
  },
  {
    id: 'SPR-003',
    title: 'Issues, Comments, Filters And Tests',
    state: 'planned',
    goal: 'Completar fluxo de issue, comentários, filtros, histórico, acessibilidade e suíte E2E MVP.',
    cards: ['OJ-BE-005', 'OJ-FE-005', 'OJ-FE-006', 'OJ-FE-007', 'OJ-021', 'OJ-025'],
  },
  {
    id: 'SPR-004',
    title: 'Release Hardening And Delivery',
    state: 'planned',
    goal: 'Fechar observabilidade, SonarQube, checks obrigatórios, docs automation, deploy, rollback e release readiness.',
    cards: ['OJ-022', 'OJ-024', 'OJ-027', 'OJ-028', 'OJ-029', 'OJ-OBS-001', 'OJ-DOC-001', 'OJ-DOC-002'],
  },
]

const baseSprintCards = [
  {
    id: 'OJ-001',
    title: 'Define product vision',
    owner: 'Mariana Costa',
    role: 'Product Strategy',
    priority: 'P0',
    status: 'done',
  },
  {
    id: 'OJ-002R',
    title: 'Restructure backlog using mandatory card model',
    owner: 'Mariana Costa',
    role: 'Product Strategy',
    priority: 'P0',
    status: 'done',
  },
  {
    id: 'OJ-003',
    title: 'Define autonomous AIA operating model',
    owner: 'Mariana Costa',
    role: 'Product Strategy',
    priority: 'P0',
    status: 'done',
  },
  {
    id: 'OJ-004',
    title: 'Create openjira-docs portal',
    owner: 'Sofia Mendes',
    role: 'Documentation',
    priority: 'P0',
    status: 'done',
  },
  {
    id: 'OJ-005',
    title: 'Publish docs remotely',
    owner: 'Camila Rocha',
    role: 'CI/CD',
    priority: 'P1',
    status: 'done',
  },
  {
    id: 'OJ-006',
    title: 'Create sprint report template',
    owner: 'Sofia Mendes',
    role: 'Documentation',
    priority: 'P0',
    status: 'done',
  },
  {
    id: 'OJ-007',
    title: 'Map core user journeys',
    owner: 'Helena Duarte',
    role: 'Requirements',
    priority: 'P0',
    status: 'done',
  },
  {
    id: 'OJ-008',
    title: 'Define functional requirements by domain',
    owner: 'Helena Duarte',
    role: 'Requirements',
    priority: 'P0',
    status: 'done',
  },
  {
    id: 'OJ-009',
    title: 'Define acceptance criteria for MVP flows',
    owner: 'Renata Barbosa',
    role: 'Quality Analyst',
    priority: 'P0',
    status: 'done',
  },
  {
    id: 'OJ-010',
    title: 'Define technical architecture',
    owner: 'Rafael Almeida',
    role: 'Tech Lead',
    priority: 'P0',
    status: 'done',
  },
  {
    id: 'OJ-011',
    title: 'Choose ORM and migration strategy',
    owner: 'Rafael Almeida',
    role: 'Tech Lead',
    priority: 'P0',
    status: 'done',
  },
  {
    id: 'OJ-012',
    title: 'Define auth and RBAC strategy',
    owner: 'Gabriel Martins',
    role: 'Backend',
    priority: 'P0',
    status: 'done',
  },
  {
    id: 'OJ-013',
    title: 'Design initial PostgreSQL model',
    owner: 'Eduardo Ribeiro',
    role: 'DBA PostgreSQL',
    priority: 'P0',
    status: 'done',
  },
  {
    id: 'OJ-014',
    title: 'Define local database strategy',
    owner: 'Eduardo Ribeiro',
    role: 'DBA PostgreSQL',
    priority: 'P0',
    status: 'done',
  },
  {
    id: 'OJ-015',
    title: 'Scaffold openjira-server',
    owner: 'Gabriel Martins',
    role: 'Backend NestJS',
    priority: 'P0',
    status: 'done',
  },
  {
    id: 'OJ-BE-001',
    title: 'Define REST API contract for MVP',
    owner: 'Gabriel Martins',
    role: 'Backend',
    priority: 'P0',
    status: 'done',
  },
  {
    id: 'OJ-019',
    title: 'Define quality gates',
    owner: 'Renata Barbosa',
    role: 'Quality Gate/QA',
    priority: 'P0',
    status: 'done',
  },
  {
    id: 'OJ-020',
    title: 'Define CI/CD baseline',
    owner: 'Camila Rocha',
    role: 'CI/CD',
    priority: 'P0',
    status: 'done',
  },
  {
    id: 'OJ-023',
    title: 'Define test pyramid and coverage policy',
    owner: 'Bruno Teixeira',
    role: 'Test Engineering',
    priority: 'P0',
    status: 'done',
  },

  {
    id: 'OJ-DB-001',
    title: 'Create PostgreSQL MVP schema',
    owner: 'Eduardo Ribeiro',
    role: 'DBA PostgreSQL',
    priority: 'P0',
    status: 'done',
  },
  {
    id: 'OJ-DB-002',
    title: 'Implement migrations and rollback',
    owner: 'Eduardo Ribeiro',
    role: 'DBA PostgreSQL / Backend',
    priority: 'P0',
    status: 'tl-review',
  },
  {
    id: 'OJ-DB-003',
    title: 'Implement local and test seeds',
    owner: 'Eduardo Ribeiro',
    role: 'DBA PostgreSQL / Backend',
    priority: 'P0',
    status: 'planned',
  },
  {
    id: 'OJ-016',
    title: 'Implement backend configuration module',
    owner: 'Gabriel Martins',
    role: 'Backend NestJS',
    priority: 'P0',
    status: 'done',
  },
  {
    id: 'OJ-BE-002',
    title: 'Implement NestJS API baseline',
    owner: 'Gabriel Martins',
    role: 'Backend NestJS',
    priority: 'P0',
    status: 'planned',
  },
  {
    id: 'OJ-AUTH-001',
    title: 'Implement authentication API',
    owner: 'Gabriel Martins',
    role: 'Backend NestJS',
    priority: 'P0',
    status: 'planned',
  },
  {
    id: 'OJ-AUTH-002',
    title: 'Implement backend RBAC',
    owner: 'Gabriel Martins',
    role: 'Backend NestJS',
    priority: 'P0',
    status: 'planned',
  },
  {
    id: 'OJ-BE-003',
    title: 'Implement organizations, members, and projects API',
    owner: 'Gabriel Martins',
    role: 'Backend NestJS',
    priority: 'P0',
    status: 'planned',
  },
  {
    id: 'OJ-017',
    title: 'Define frontend app shell and navigation',
    owner: 'Lucas Ferreira',
    role: 'Frontend Next.js',
    priority: 'P0',
    status: 'planned',
  },
  {
    id: 'OJ-FE-001',
    title: 'Define Next.js route map',
    owner: 'Lucas Ferreira',
    role: 'Frontend Next.js',
    priority: 'P0',
    status: 'planned',
  },
  {
    id: 'OJ-FE-002',
    title: 'Implement login UI and auth states',
    owner: 'Lucas Ferreira',
    role: 'Frontend Next.js',
    priority: 'P0',
    status: 'planned',
  },
  {
    id: 'OJ-FE-003',
    title: 'Implement organization and project selection UI',
    owner: 'Lucas Ferreira',
    role: 'Frontend Next.js',
    priority: 'P0',
    status: 'planned',
  },
  {
    id: 'OJ-026',
    title: 'Create evidence templates',
    owner: 'Sofia Mendes',
    role: 'Documentation',
    priority: 'P0',
    status: 'done',
  },
]

const sharedDoneExpectations = {
  testExpectations: ['Validar consistência do documento fonte e links referenciados.'],
  qaExpectations: ['Confirmar que o artefato atende ao workflow AIA e não deixa campo obrigatório em aberto.'],
  documentationExpectations: ['Manter Markdown versionado e rastreável no portal.'],
}

const cardDetails = {
  'OJ-001': {
    assignee: 'Mariana Costa',
    tags: ['Produto', 'Visão', 'MVP'],
    dependencies: [],
    evidence: ['docs/product/mvp-backlog.md'],
    description: 'Define a visão de produto e o recorte de MVP usado pela AIA.',
    acceptanceCriteria: ['Visão do produto registrada.', 'Escopo do MVP descrito.', 'Documento publicado no portal.'],
    nextAction: 'Manter como referência para priorização das próximas sprints.',
    sourcePath: 'docs/product/mvp-backlog.md',
    ...sharedDoneExpectations,
  },
  'OJ-002R': {
    assignee: 'Mariana Costa',
    tags: ['Backlog', 'Card model', 'Governança'],
    dependencies: ['OJ-001'],
    evidence: ['docs/product/mvp-backlog.md'],
    description: 'Reestrutura o backlog usando o card model obrigatório da AIA.',
    acceptanceCriteria: ['Cards possuem dono, prioridade, dependências e critérios.', 'Backlog está versionado.', 'Cards futuros permanecem fora da execução até aprovação.'],
    nextAction: 'Usar backlog como fonte principal para planejamento da SPR-000.',
    sourcePath: 'docs/product/mvp-backlog.md',
    ...sharedDoneExpectations,
  },
  'OJ-003': {
    assignee: 'Mariana Costa',
    tags: ['AIA', 'Workflow', 'Operação'],
    dependencies: ['OJ-001'],
    evidence: ['docs/operations/aia-delivery-workflow.md'],
    description: 'Define o modelo operacional autônomo da squad AIA.',
    acceptanceCriteria: ['Papéis descritos.', 'Fluxo de retorno e priorização registrado.', 'Limites de atuação por função definidos.'],
    nextAction: 'Aplicar o fluxo em todo card novo ou retornado por QA, tester ou TechLead.',
    sourcePath: 'docs/operations/aia-delivery-workflow.md',
    ...sharedDoneExpectations,
  },
  'OJ-004': {
    assignee: 'Sofia Mendes',
    tags: ['Portal', 'Documentação', 'Vite'],
    dependencies: ['OJ-001', 'OJ-003'],
    evidence: ['src/main.js', 'src/content.js', 'src/styles.scss'],
    description: 'Cria o portal estático OpenJira Docs para acompanhar produto, sprints e governança.',
    acceptanceCriteria: ['Portal executa localmente.', 'Conteúdo operacional é renderizado.', 'Build Vite passa sem erro.'],
    nextAction: 'Evoluir para Manager View após validação de UX e TechLead.',
    sourcePath: 'src/main.js',
    ...sharedDoneExpectations,
  },
  'OJ-005': {
    assignee: 'Camila Rocha',
    tags: ['CI/CD', 'Deploy', 'GitHub Pages'],
    dependencies: ['OJ-004'],
    evidence: ['.github/workflows/pages.yml', 'https://editorastudiowriter.github.io/openjira-docs/'],
    description: 'Publica o portal remoto em GitHub Pages via GitHub Actions.',
    acceptanceCriteria: ['GitHub Pages selecionado.', 'Pipeline de build configurado.', 'URL de produção registrada.'],
    testExpectations: ['Validar build em CI e acesso ao artefato publicado.'],
    qaExpectations: ['Confirmar que a URL entrega a versão correta e que o conteúdo sensível não foi exposto indevidamente.'],
    documentationExpectations: ['Registrar URL, estratégia de deploy e fallback operacional.'],
    nextAction: 'Manter publicação automática pela branch main e acompanhar mudanças pela branch development.',
    sourcePath: 'docs/product/mvp-backlog.md',
  },
  'OJ-006': {
    assignee: 'Sofia Mendes',
    tags: ['Sprint', 'Relatório', 'Documentação'],
    dependencies: ['OJ-003'],
    evidence: ['docs/sprints/report-template.md'],
    description: 'Cria o template de relatório final de sprint.',
    acceptanceCriteria: ['Template possui entregas, riscos, métricas, pendências e decisão recomendada.', 'Formato pode ser reutilizado por sprint.'],
    nextAction: 'Usar o template no encerramento da SPR-000.',
    sourcePath: 'docs/sprints/report-template.md',
    ...sharedDoneExpectations,
  },
  'OJ-007': {
    assignee: 'Helena Duarte',
    tags: ['Requisitos', 'Jornadas', 'Done'],
    dependencies: [],
    evidence: ['docs/requirements/core-user-journeys.md'],
    description: 'Mapeia as jornadas centrais do usuário para orientar requisitos, aceitação e testes.',
    acceptanceCriteria: ['Jornadas de autenticação, organização, projeto, board e issue estão descritas.', 'Atores e resultados esperados estão claros.', 'Artefato está pronto para alimentar OJ-008 e OJ-009.'],
    testExpectations: ['Transformar jornadas críticas em cenários de aceitação e E2E quando a UI existir.'],
    qaExpectations: ['Validar cobertura das jornadas essenciais do MVP.'],
    documentationExpectations: ['Manter o documento de jornadas como evidência primária.'],
    nextAction: 'Usar como evidência aceita para concluir OJ-008.',
    sourcePath: 'docs/requirements/core-user-journeys.md',
  },
  'OJ-008': {
    assignee: 'Helena Duarte',
    tags: ['Requisitos', 'Domínios', 'Done'],
    dependencies: ['OJ-007'],
    evidence: ['docs/requirements/functional-requirements-matrix.md'],
    description: 'Define requisitos funcionais por domínio do MVP.',
    acceptanceCriteria: ['Domínios do MVP têm requisitos rastreáveis.', 'Requisitos citam jornadas relevantes.', 'Lacunas são marcadas para TechLead.'],
    testExpectations: ['Permitir derivar critérios de aceitação por fluxo.'],
    qaExpectations: ['Revisar ambiguidade, completude e dependências.'],
    documentationExpectations: ['Atualizar backlog e docs de requisitos.'],
    nextAction: 'Usar como evidência aceita para concluir OJ-009 e OJ-010.',
    sourcePath: 'docs/requirements/functional-requirements-matrix.md',
  },
  'OJ-009': {
    assignee: 'Renata Barbosa',
    tags: ['QA', 'Aceitação', 'MVP'],
    dependencies: ['OJ-007', 'OJ-008'],
    evidence: ['docs/quality/mvp-acceptance-criteria.md'],
    description: 'Define critérios de aceitação para os fluxos MVP.',
    acceptanceCriteria: ['Critérios cobrem happy path e falhas principais.', 'Critérios são objetivos e testáveis.', 'Cada fluxo crítico tem resultado esperado.'],
    testExpectations: ['Gerar base para testes de integração e E2E.'],
    qaExpectations: ['Bloquear critérios subjetivos ou sem evidência verificável.'],
    documentationExpectations: ['Publicar critérios no backlog e documentos de qualidade.'],
    nextAction: 'Usar como evidência aceita para concluir OJ-019 e OJ-023.',
    sourcePath: 'docs/quality/mvp-acceptance-criteria.md',
  },
  'OJ-010': {
    assignee: 'Rafael Almeida',
    tags: ['Arquitetura', 'Tech Lead', 'Decisão'],
    dependencies: ['OJ-008'],
    evidence: ['docs/architecture/technical-architecture.md'],
    description: 'Define a arquitetura técnica base do OpenJira.',
    acceptanceCriteria: ['Frontend, backend, banco, autenticação e deploy têm direção técnica.', 'Riscos e decisões estão registrados.', 'Dependências para CI/CD são explícitas.'],
    testExpectations: ['Indicar impactos em testes unitários, integração e E2E.'],
    qaExpectations: ['Verificar rastreabilidade entre arquitetura, requisitos e qualidade.'],
    documentationExpectations: ['Registrar decisões arquiteturais em Markdown.'],
    nextAction: 'Usar como evidência aceita para concluir OJ-011, OJ-012 e OJ-015.',
    sourcePath: 'docs/architecture/technical-architecture.md',
  },
  'OJ-011': {
    assignee: 'Rafael Almeida',
    tags: ['ORM', 'Migrations', 'Banco'],
    dependencies: ['OJ-010'],
    evidence: ['docs/architecture/technical-architecture.md'],
    description: 'Escolhe ORM e estratégia de migração para o backend NestJS.',
    acceptanceCriteria: ['ORM selecionado.', 'Estratégia de migration e rollback definida.', 'Integração com PostgreSQL documentada.'],
    testExpectations: ['Prever testes de migration e fixtures.'],
    qaExpectations: ['Validar que a escolha suporta auditoria, CI e ambientes locais.'],
    documentationExpectations: ['Registrar decisão e comandos principais.'],
    nextAction: 'Produzir docs/architecture/orm-migration-strategy.md para destravar OJ-013.',
    sourcePath: 'docs/product/mvp-backlog.md',
  },
  'OJ-012': {
    assignee: 'Gabriel Martins',
    tags: ['Auth', 'RBAC', 'Backend'],
    dependencies: ['OJ-008', 'OJ-010'],
    evidence: ['docs/architecture/technical-architecture.md', 'docs/requirements/functional-requirements-matrix.md'],
    description: 'Define estratégia de autenticação e autorização por papéis.',
    acceptanceCriteria: ['Fluxo de login e sessão definido.', 'Papéis e permissões MVP descritos.', 'Riscos de segurança registrados.'],
    testExpectations: ['Definir cenários de permissão negada, expiração e acesso permitido.'],
    qaExpectations: ['Validar coerência com jornadas e requisitos.'],
    documentationExpectations: ['Atualizar docs de backend e requisitos.'],
    nextAction: 'Produzir docs/architecture/auth-rbac-strategy.md para destravar OJ-013.',
    sourcePath: 'docs/product/mvp-backlog.md',
  },
  'OJ-013': {
    assignee: 'Eduardo Ribeiro',
    tags: ['PostgreSQL', 'Modelo de dados', 'DBA'],
    dependencies: ['OJ-011', 'OJ-012'],
    evidence: ['docs/product/mvp-backlog.md'],
    description: 'Desenha o modelo PostgreSQL inicial para organizações, projetos, issues e usuários.',
    acceptanceCriteria: ['Entidades principais descritas.', 'Relacionamentos e chaves identificados.', 'Restrições e índices candidatos registrados.'],
    testExpectations: ['Prever fixtures e validações de integridade.'],
    qaExpectations: ['Verificar suporte aos fluxos MVP e histórico básico.'],
    documentationExpectations: ['Adicionar diagrama ou tabela de modelo de dados.'],
    nextAction: 'Revisar com Rafael depois da estratégia de ORM e RBAC.',
    sourcePath: 'docs/product/mvp-backlog.md',
  },
  'OJ-014': {
    assignee: 'Eduardo Ribeiro',
    tags: ['Banco local', 'Docker', 'PostgreSQL'],
    dependencies: ['OJ-013'],
    evidence: ['docs/product/mvp-backlog.md'],
    description: 'Define estratégia de banco local para desenvolvimento e testes.',
    acceptanceCriteria: ['Ambiente local é reproduzível.', 'Seeds e reset são previstos.', 'Dependências de CI/CD estão claras.'],
    testExpectations: ['Suportar execução automatizada de testes com banco limpo.'],
    qaExpectations: ['Confirmar que a estratégia evita estado compartilhado entre testes.'],
    documentationExpectations: ['Documentar comandos de setup, reset e troubleshooting.'],
    nextAction: 'Aguardar modelo inicial e alinhar com CI/CD.',
    sourcePath: 'docs/product/mvp-backlog.md',
  },
  'OJ-015': {
    assignee: 'Gabriel Martins',
    tags: ['NestJS', 'Scaffold', 'Backend'],
    dependencies: ['OJ-010'],
    evidence: ['docs/product/mvp-backlog.md'],
    description: 'Cria o scaffold do backend NestJS.',
    acceptanceCriteria: ['Projeto backend inicial criado.', 'Scripts principais definidos.', 'Build e lint mínimos executam.'],
    testExpectations: ['Adicionar teste inicial de saúde do projeto.'],
    qaExpectations: ['Validar que o scaffold segue decisões técnicas aprovadas.'],
    documentationExpectations: ['Registrar comandos de desenvolvimento no README do backend.'],
    nextAction: 'Não iniciar até arquitetura técnica estar aprovada.',
    sourcePath: 'docs/product/mvp-backlog.md',
  },
  'OJ-BE-001': {
    assignee: 'Gabriel Martins',
    tags: ['API', 'Contrato', 'Backend'],
    dependencies: ['OJ-007', 'OJ-008', 'OJ-010', 'OJ-013'],
    evidence: ['docs/product/mvp-backlog.md'],
    description: 'Define o contrato REST inicial para o MVP.',
    acceptanceCriteria: ['Endpoints principais mapeados.', 'Payloads e erros documentados.', 'Contrato cobre jornadas MVP.'],
    testExpectations: ['Basear testes de integração no contrato aprovado.'],
    qaExpectations: ['Validar consistência entre contrato, critérios de aceitação e requisitos.'],
    documentationExpectations: ['Publicar contrato em Markdown ou OpenAPI quando definido.'],
    nextAction: 'Aguardar requisitos e critérios de aceitação.',
    sourcePath: 'docs/product/mvp-backlog.md',
  },
  'OJ-017': {
    assignee: 'Lucas Ferreira',
    tags: ['Frontend', 'Next.js', 'Navegação'],
    dependencies: ['OJ-010', 'OJ-012'],
    evidence: ['docs/sprints/sprint-001-plan.md', 'docs/design/openjira-manager-view-ui-report.md'],
    description: 'Define app shell e navegação do frontend Next.js.',
    acceptanceCriteria: ['Estrutura de navegação aprovada.', 'Rotas principais do MVP mapeadas.', 'Estados de loading, vazio e erro previstos.'],
    testExpectations: ['Prever cobertura de navegação e renderização principal.'],
    qaExpectations: ['Validar acessibilidade e clareza dos fluxos.'],
    documentationExpectations: ['Registrar decisões de shell e navegação.'],
    nextAction: 'Preparar app shell e navegação antes do route map.',
    sourcePath: 'docs/product/mvp-backlog.md',
  },
  'OJ-018': {
    assignee: 'Beatriz Nogueira',
    tags: ['UX/UI', 'Board', 'MVP'],
    dependencies: ['OJ-007', 'OJ-008'],
    evidence: ['docs/design/openjira-manager-view-ui-report.md'],
    description: 'Define telas MVP e regras de UX/UI do board.',
    acceptanceCriteria: ['Telas principais descritas.', 'Regras de board e interação registradas.', 'Fluxos móveis e desktop considerados.'],
    testExpectations: ['Definir expectativas de acessibilidade e estados visuais.'],
    qaExpectations: ['Rafael valida se proposta é implementável e alinhada ao MVP.'],
    documentationExpectations: ['Manter relatório de UX com wireframes e Mermaid.'],
    nextAction: 'Usar relatório como contrato para implementação visual do portal.',
    sourcePath: 'docs/design/openjira-manager-view-ui-report.md',
  },
  'OJ-019': {
    assignee: 'Renata Barbosa',
    tags: ['Quality Gate', 'QA', 'Política'],
    dependencies: ['OJ-009'],
    evidence: ['docs/quality/mvp-acceptance-criteria.md', 'docs/quality/test-policy.md'],
    description: 'Define quality gates mínimos para aceitar entregas da AIA.',
    acceptanceCriteria: ['Gates mínimos são objetivos.', 'Falhas bloqueantes estão claras.', 'Responsabilidades de QA, tester e TechLead são explícitas.'],
    testExpectations: ['Amarrar lint, build, testes e evidências aos gates.'],
    qaExpectations: ['Garantir que nenhum card avance sem evidência suficiente.'],
    documentationExpectations: ['Atualizar política de qualidade.'],
    nextAction: 'Produzir docs/quality/quality-gates.md para destravar OJ-023 e OJ-020.',
    sourcePath: 'docs/quality/test-policy.md',
  },
  'OJ-020': {
    assignee: 'Camila Rocha',
    tags: ['CI/CD', 'Pipeline', 'Baseline'],
    dependencies: ['OJ-010', 'OJ-014', 'OJ-019', 'OJ-023'],
    evidence: ['docs/product/mvp-backlog.md'],
    description: 'Define baseline de CI/CD para build, testes e publicação.',
    acceptanceCriteria: ['Pipeline mínimo descrito.', 'Checks obrigatórios mapeados.', 'Estratégia de artefatos e evidências definida.'],
    testExpectations: ['Pipeline deve executar validações automáticas exigidas pelos gates.'],
    qaExpectations: ['QA confirma que falhas impedem avanço indevido.'],
    documentationExpectations: ['Registrar jobs, variáveis, ambientes e evidências.'],
    nextAction: 'Aguardar arquitetura, banco local, quality gates e política de testes.',
    sourcePath: 'docs/product/mvp-backlog.md',
  },
  'OJ-023': {
    assignee: 'Bruno Teixeira',
    tags: ['Testes', 'Cobertura', 'Política'],
    dependencies: ['OJ-009', 'OJ-019'],
    evidence: ['docs/quality/test-policy.md'],
    description: 'Define pirâmide de testes e política de cobertura.',
    acceptanceCriteria: ['Camadas de teste estão definidas.', 'Cobertura mínima por tipo de mudança está clara.', 'Política não depende da estratégia executável de E2E futura.'],
    testExpectations: ['Servir como base para estratégia de integração e E2E em OJ-021.'],
    qaExpectations: ['Validar que a política é aplicável já na fundação.'],
    documentationExpectations: ['Atualizar docs de qualidade e backlog.'],
    nextAction: 'Rafael deve revisar após OJ-019.',
    sourcePath: 'docs/quality/test-policy.md',
  },

  'OJ-DB-001': {
    assignee: 'Eduardo Ribeiro',
    tags: ['SPR-001', 'PostgreSQL', 'Schema'],
    dependencies: ['OJ-011', 'OJ-013'],
    evidence: ['docs/evidence/sprint-001-oj-db-001-oj-016.md', 'docs/sprints/sprint-001-plan.md', 'docs/architecture/postgresql-mvp-data-model.md'],
    description: 'Implementa o schema PostgreSQL MVP com isolamento por organização/projeto.',
    acceptanceCriteria: ['Schema cria entidades MVP.', 'FKs, uniques, timestamps e índices principais existem.', 'Campos de isolamento multi-tenant estão presentes.'],
    testExpectations: ['Criar schema do zero em PostgreSQL.', 'Validar constraints e índices esperados.'],
    qaExpectations: ['Confirmar que nenhuma entidade MVP crítica ficou ausente.'],
    documentationExpectations: ['Registrar comandos e evidência de criação do schema.'],
    nextAction: 'Concluído; próxima dependência é fechar OJ-DB-002 rollback/CI e OJ-DB-003 seeds.',
    sourcePath: 'docs/product/mvp-backlog.md',
  },
  'OJ-DB-002': {
    assignee: 'Gabriel Martins',
    tags: ['SPR-001', 'Prisma', 'Migrations'],
    dependencies: ['OJ-011', 'OJ-DB-001'],
    evidence: ['docs/evidence/sprint-001-oj-db-002.md', 'docs/sprints/sprint-001-plan.md', 'docs/architecture/orm-migration-strategy.md'],
    description: 'Implementa migration inicial, deploy, drift check e política de rollback/forward-fix. Branch e PR estão prontos para revisão técnica.',
    acceptanceCriteria: ['Migration inicial existe.', 'Comandos local/test/deploy estão documentados.', 'Rollback ou forward-fix está evidenciado.'],
    testExpectations: ['Executar migration em banco limpo.', 'Validar ausência de drift.'],
    qaExpectations: ['Confirmar que migration falha de forma segura quando inválida.'],
    documentationExpectations: ['Registrar evidência de migration e rollback/forward-fix.'],
    nextAction: 'Rafael deve revisar o PR do backend e decidir se CI de migrations entra neste card ou em card de CI/CD.',
    sourcePath: 'docs/product/mvp-backlog.md',
  },
  'OJ-DB-003': {
    assignee: 'Gabriel Martins',
    tags: ['SPR-001', 'Seeds', 'Test data'],
    dependencies: ['OJ-DB-002'],
    evidence: ['docs/sprints/sprint-001-plan.md', 'docs/evidence/index.md'],
    description: 'Cria seeds idempotentes para ambiente local e testes.',
    acceptanceCriteria: ['Seeds são idempotentes.', 'Dados cobrem usuários, organizações, papéis, projeto, board, issues, comentários e histórico.', 'Seeds suportam teste manual e automatizado.'],
    testExpectations: ['Executar seed duas vezes sem duplicar dados.', 'Validar usuários e relações essenciais.'],
    qaExpectations: ['Confirmar que demo data cobre fluxos MVP iniciais.'],
    documentationExpectations: ['Registrar credenciais fictícias e comandos sem expor segredo real.'],
    nextAction: 'Executar depois de migrations estáveis.',
    sourcePath: 'docs/product/mvp-backlog.md',
  },
  'OJ-016': {
    assignee: 'Gabriel Martins',
    tags: ['SPR-001', 'Backend', 'Config'],
    dependencies: ['OJ-015'],
    evidence: ['docs/evidence/sprint-001-oj-db-001-oj-016.md', 'docs/sprints/sprint-001-plan.md', 'docs/architecture/backend-scaffold-evidence.md'],
    description: 'Implementa configuração validada para runtime, banco, auth, CORS, logging e testes.',
    acceptanceCriteria: ['Env inválido falha rápido.', 'DATABASE_URL e TEST_DATABASE_URL são suportadas.', 'CORS com credenciais não usa wildcard.'],
    testExpectations: ['Testar env válido e inválido.', 'Build e lint passam.'],
    qaExpectations: ['Confirmar que nenhum segredo real entra em arquivo versionado.'],
    documentationExpectations: ['Atualizar README/env example do backend.'],
    nextAction: 'Concluído; OJ-BE-002 pode usar configuração validada.',
    sourcePath: 'docs/product/mvp-backlog.md',
  },
  'OJ-BE-002': {
    assignee: 'Gabriel Martins',
    tags: ['SPR-001', 'API baseline', 'NestJS'],
    dependencies: ['OJ-015', 'OJ-016'],
    evidence: ['docs/sprints/sprint-001-plan.md', 'docs/architecture/rest-api-contract-mvp.md'],
    description: 'Cria baseline de API com validação, erro padrão, logs, request id, Swagger, CORS e readiness.',
    acceptanceCriteria: ['Validation pipe global ativo.', 'Exception filter usa formato padrão.', 'Swagger e health/live/ready existem.'],
    testExpectations: ['Validar health live sem banco e ready com banco.', 'Testar erro padrão com requestId.'],
    qaExpectations: ['Confirmar que DTOs rejeitam payload inválido.'],
    documentationExpectations: ['Registrar endpoints técnicos e evidência Swagger.'],
    nextAction: 'Executar depois de OJ-016.',
    sourcePath: 'docs/product/mvp-backlog.md',
  },
  'OJ-AUTH-001': {
    assignee: 'Gabriel Martins',
    tags: ['SPR-001', 'Auth', 'Security'],
    dependencies: ['OJ-012', 'OJ-BE-002', 'OJ-DB-002'],
    evidence: ['docs/sprints/sprint-001-plan.md', 'docs/architecture/auth-rbac-strategy.md'],
    description: 'Implementa login, sessão HttpOnly, CSRF/session hardening, current user e guards.',
    acceptanceCriteria: ['Login funciona para usuário seed.', 'Senha é hasheada.', 'Rotas privadas exigem autenticação.', 'Falhas usam erro genérico seguro.'],
    testExpectations: ['Testar login válido, credencial inválida e rota privada sem sessão.'],
    qaExpectations: ['Confirmar que erro não revela se usuário existe.'],
    documentationExpectations: ['Registrar política de sessão/CSRF aplicada.'],
    nextAction: 'Não iniciar antes de OJ-BE-002 e migrations.',
    sourcePath: 'docs/product/mvp-backlog.md',
  },
  'OJ-AUTH-002': {
    assignee: 'Gabriel Martins',
    tags: ['SPR-001', 'RBAC', 'Security'],
    dependencies: ['OJ-012', 'OJ-DB-001', 'OJ-AUTH-001'],
    evidence: ['docs/sprints/sprint-001-plan.md', 'docs/architecture/auth-rbac-strategy.md'],
    description: 'Implementa autorização backend por organização, projeto e recurso.',
    acceptanceCriteria: ['Membership é verificado no backend.', 'Papéis controlam ações protegidas.', 'Acesso negado retorna 403 seguro.'],
    testExpectations: ['Testar viewer read-only, member permitido e negação cross-org/cross-project.'],
    qaExpectations: ['Confirmar que frontend não consegue burlar autorização.'],
    documentationExpectations: ['Registrar matriz implementada e evidência de negação.'],
    nextAction: 'Executar depois de auth básica.',
    sourcePath: 'docs/product/mvp-backlog.md',
  },
  'OJ-BE-003': {
    assignee: 'Gabriel Martins',
    tags: ['SPR-001', 'Organizations', 'Projects'],
    dependencies: ['OJ-AUTH-002', 'OJ-DB-002'],
    evidence: ['docs/sprints/sprint-001-plan.md', 'docs/architecture/rest-api-contract-mvp.md'],
    description: 'Implementa APIs de organizações, membros e projetos escopadas ao usuário autenticado.',
    acceptanceCriteria: ['Usuário lista organizações acessíveis.', 'Usuário lista/cria projetos quando permitido.', 'Acesso não autorizado é negado sem vazamento.'],
    testExpectations: ['Testes de integração para listagem, criação e negação segura.'],
    qaExpectations: ['Confirmar isolamento entre organizações/projetos.'],
    documentationExpectations: ['Registrar endpoints implementados e Swagger.'],
    nextAction: 'Executar depois de RBAC.',
    sourcePath: 'docs/product/mvp-backlog.md',
  },
  'OJ-FE-001': {
    assignee: 'Lucas Ferreira',
    tags: ['SPR-001', 'Next.js', 'Routes'],
    dependencies: ['OJ-017', 'OJ-BE-001'],
    evidence: ['docs/sprints/sprint-001-plan.md', 'docs/design/openjira-manager-view-ui-report.md'],
    description: 'Define rotas, layouts, permissões, data requirements e estados de fallback do MVP.',
    acceptanceCriteria: ['Rotas de login, seleção org/projeto, board, issue detail, 403, 404 e erro são mapeadas.', 'Cada rota declara auth e data source.', 'Loading/error/fallback são planejados.'],
    testExpectations: ['Validar mapa contra contrato REST e requisitos.'],
    qaExpectations: ['Confirmar que rotas protegidas não expõem dados anônimos.'],
    documentationExpectations: ['Registrar route map como evidência.'],
    nextAction: 'Executar depois de OJ-017.',
    sourcePath: 'docs/product/mvp-backlog.md',
  },
  'OJ-FE-002': {
    assignee: 'Lucas Ferreira',
    tags: ['SPR-001', 'Login UI', 'Auth states'],
    dependencies: ['OJ-AUTH-001', 'OJ-FE-001'],
    evidence: ['docs/sprints/sprint-001-plan.md', 'docs/evidence/tester-success.md'],
    description: 'Implementa tela de login, validação, loading, erro seguro, sessão expirada e redirect pós-login.',
    acceptanceCriteria: ['Campos obrigatórios validam.', 'Loading evita submit duplicado.', 'Erro API é claro e seguro.', 'Login bem-sucedido redireciona corretamente.'],
    testExpectations: ['Testar sucesso, falha, submit duplicado e sessão expirada.'],
    qaExpectations: ['Validar acessibilidade e mensagens seguras.'],
    documentationExpectations: ['Registrar evidência visual e comandos de validação.'],
    nextAction: 'Executar depois de auth API e route map.',
    sourcePath: 'docs/product/mvp-backlog.md',
  },
  'OJ-FE-003': {
    assignee: 'Lucas Ferreira',
    tags: ['SPR-001', 'Organizations', 'Projects'],
    dependencies: ['OJ-BE-003', 'OJ-FE-001'],
    evidence: ['docs/sprints/sprint-001-plan.md', 'docs/evidence/tester-success.md'],
    description: 'Implementa UI para listar e selecionar organizações/projetos acessíveis.',
    acceptanceCriteria: ['Organizações acessíveis são listadas.', 'Projetos aparecem sob organização selecionada.', 'Estados vazio e sem permissão existem.'],
    testExpectations: ['Testar lista populada, vazia e sem acesso.'],
    qaExpectations: ['Confirmar que dados restritos não aparecem em estados de erro.'],
    documentationExpectations: ['Registrar evidência visual e estados testados.'],
    nextAction: 'Executar depois de API de organizações/projetos.',
    sourcePath: 'docs/product/mvp-backlog.md',
  },
  'OJ-026': {
    assignee: 'Sofia Mendes',
    tags: ['Evidências', 'Templates', 'Ready'],
    dependencies: [],
    evidence: ['docs/evidence/index.md', 'docs/evidence/qa-gate.md', 'docs/evidence/release-evidence.md'],
    description: 'Cria templates de evidência para sucesso, falha, QA, SonarQube, deploy e release.',
    acceptanceCriteria: ['Templates existem para cenários principais.', 'Campos obrigatórios estão claros.', 'Evidências são reutilizáveis por sprint.'],
    testExpectations: ['Tester consegue registrar sucesso e falha com passos reproduzíveis.'],
    qaExpectations: ['QA consegue aprovar ou reprovar usando o template.'],
    documentationExpectations: ['Indexar todos os templates em docs/evidence/index.md.'],
    nextAction: 'Planejar na sprint e exigir uso nos próximos retornos de QA/tester.',
    sourcePath: 'docs/evidence/index.md',
  },
}

export const sprintCards = baseSprintCards.map((card) => ({
  assignee: card.owner,
  tags: [],
  dependencies: [],
  evidence: [],
  description: '',
  acceptanceCriteria: [],
  testExpectations: [],
  qaExpectations: [],
  documentationExpectations: [],
  nextAction: '',
  sourcePath: 'docs/product/mvp-backlog.md',
  ...card,
  ...cardDetails[card.id],
}))

export const workflowColumns = [
  { id: 'ready-for-sprint', title: 'Ready for Sprint', empty: 'Nenhum card pronto para sprint.' },
  { id: 'tl-review', title: 'TL Review', empty: 'Nenhum card aguardando TechLead.' },
  { id: 'planned', title: 'Planejado', empty: 'Nenhum card planejado.' },
  { id: 'in-development', title: 'Em desenvolvimento', empty: 'Nenhum card em desenvolvimento.' },
  { id: 'blocked', title: 'Bloqueado', empty: 'Nenhum bloqueio registrado.' },
  { id: 'done', title: 'Concluído', empty: 'Nada concluído ainda.' },
]
