export const docs = [
  {
    id: 'remote-access',
    label: 'Acesso remoto',
    eyebrow: 'Recomendação',
    title: 'Portal estático publicado por CI',
    summary:
      'O OpenJira Docs deve ser um site estático versionado, publicado automaticamente em Cloudflare Pages ou GitHub Pages.',
    items: [
      'Projeto dedicado: openjira-docs, independente do frontend e do backend.',
      'Deploy recomendado: Cloudflare Pages para preview por branch, domínio customizado e CDN global.',
      'Alternativa simples: GitHub Pages com GitHub Actions para publicar a pasta dist.',
      'Conteúdo versionado junto ao código para manter histórico de decisões, sprints e relatórios.',
      'Sem dependência de banco ou servidor para leitura dos documentos.',
    ],
  },
  {
    id: 'agency-governance',
    label: 'Governança AIA',
    eyebrow: 'Operating model',
    title: 'Squad autônoma com workflow obrigatório',
    summary:
      'A AIA opera de forma independente, mas todo trabalho deve passar pelo fluxo de backlog, card, desenvolvimento, teste, QA, review e documentação.',
    items: [
      'Gestão: Mariana, TechLead e Analista de Requisitos definem e validam backlog item por item.',
      'Mariana cria épicos e cards completos, com requisitos, dependências, critérios, evidências e links de KB.',
      'TechLead revisa cards, atribui conforme especialidade e senioridade, faz code review final e decide PR.',
      'Developers implementam, testam, criam testes, commitam e notificam tester.',
      'Tester e QA nunca corrigem código; retornam cards com evidências, tags e prioridade quando falhar.',
      'Documentarista atualiza Markdown e usa Mermaid quando o fluxo, arquitetura ou decisão exigir clareza visual.',
    ],
  },
  {
    id: 'delivery-workflow',
    label: 'Workflow',
    eyebrow: 'Lei operacional',
    title: 'Fluxo obrigatório antes de qualquer execução',
    summary:
      'Nenhum membro trabalha fora do próprio escopo. Cada card precisa passar pelo ciclo formal de gestão, desenvolvimento, qualidade, review e documentação.',
    items: [
      'Documento fonte: docs/operations/aia-delivery-workflow.md.',
      'Management team: PM Mariana, TechLead e Analista de Requisitos.',
      'A Mariana solicita acessos por meio da equipe de infra.',
      'Cards retornados por tester, QA ou TechLead tem prioridade sobre novas tasks, sempre pelo mais antigo.',
      'Tags obrigatórias para retorno: URGENTE, BUG, TESTER, QA, SONARQUBE, CODE_REVIEW e DEBITO_TECNICO.',
    ],
  },
  {
    id: 'product-vision',
    label: 'Visão',
    eyebrow: 'Produto',
    title: 'OpenJira como ferramenta de gestão de trabalho',
    summary:
      'O OpenJira é uma ferramenta web para times de produto, engenharia e operações organizarem projetos, tarefas, prioridades e entregas.',
    items: [
      'Foco em Kanban e Scrum para times pequenos e médios.',
      'Experiência densa, clara e adequada ao uso recorrente.',
      'Backend próprio em NestJS com PostgreSQL.',
      'Frontend próprio em Next.js.',
      'APIs documentadas para automação e integrações futuras.',
    ],
  },
  {
    id: 'mvp',
    label: 'MVP',
    eyebrow: 'Escopo',
    title: 'Validar um projeto real do início ao fim',
    summary:
      'O MVP deve provar que um time consegue autenticar, criar projetos, gerir issues e acompanhar o fluxo pelo board.',
    items: [
      'Autenticação de usuários.',
      'Organizações, membros e projetos.',
      'Board Kanban por projeto.',
      'Issues com tipo, prioridade, responsável, status e comentários.',
      'Drag and drop entre colunas.',
      'Histórico básico de mudanças e filtros essenciais.',
    ],
  },
  {
    id: 'sprints',
    label: 'Sprints',
    eyebrow: 'Execução',
    title: 'Cadência autônoma com gate de TechLead',
    summary:
      'As sprints são planejadas pela AIA, mas cards de implementação só entram em execução depois de card completo, dependências explícitas e TechLead review.',
    items: [
      'Sprint 000: fundação, workflow AIA, backlog completo, docs, arquitetura, dados, qualidade e CI/CD baseline.',
      'Sprint 001: autenticação, RBAC, organizações, projetos, banco inicial e app shell.',
      'Sprint 002: board Kanban, colunas, movimentação transacional, rotas Next.js e UI do board.',
      'Sprint 003: issues, comentários, histórico, filtros, acessibilidade e testes E2E MVP.',
      'Sprint 004: hardening, SonarQube, required checks, deploy, rollback, evidências e release readiness.',
    ],
  },
  {
    id: 'quality-gates',
    label: 'Quality gates',
    eyebrow: 'Qualidade',
    title: 'Quality gates em definição na Sprint 000',
    summary:
      'A política final depende da aprovação do card OJ-019, mas o workflow já exige validação objetiva antes de considerar uma entrega pronta.',
    items: [
      'Card fonte: OJ-019 - Define quality gates.',
      'Critérios candidatos: lint, formatação, typecheck e build aprovados.',
      'Testes unitários e integração para áreas alteradas entram na política.',
      'Fluxos críticos devem ser cobertos por E2E quando houver interface pronta.',
      'SonarQube e required checks dependem dos cards OJ-022 e OJ-024.',
      'Documentação deve ser atualizada quando houver mudança funcional, técnica ou operacional.',
    ],
  },
  {
    id: 'task-board',
    label: 'Tasks',
    eyebrow: 'Backlog',
    title: 'Backlog MVP e Sprint 000 ativos',
    summary:
      'A AIA reestruturou o backlog usando o card model obrigatório. A SPR-000 está ativa para grooming e TechLead review, mas ainda não está pronta para execução ampla.',
    items: [
      'Backlog: docs/product/mvp-backlog.md.',
      'Sprint ativa: docs/sprints/sprint-000-plan.md.',
      'Roadmap: docs/sprints/sprint-001-plan.md até docs/sprints/sprint-004-plan.md.',
      'Template de relatório: docs/sprints/report-template.md.',
      'Status atual: OJ-007 e OJ-026 foram destravados internamente e estão em Ready for Sprint.',
      'Próximo foco autônomo: executar OJ-008 depois da aceitação de OJ-007 e seguir a cadeia fundacional definida pelo TechLead.',
    ],
  },
]

export const agents = [
  'Mariana Costa - Product Strategy',
  'Helena Duarte - Requisitos',
  'Rafael Almeida - Tech Lead',
  'Beatriz Nogueira - UX/UI',
  'Lucas Ferreira - Frontend Next.js',
  'Gabriel Martins - Backend NestJS',
  'Eduardo Ribeiro - DBA PostgreSQL',
  'Camila Rocha - CI/CD',
  'Bruno Teixeira - Testes Integração/E2E/P2P',
  'Renata Barbosa - Quality Gate/QA',
  'Sofia Mendes - Documentação',
]

export const sprintStatus = {
  id: 'SPR-000',
  name: 'Foundation And Operating Model',
  state: 'active',
  startedAt: '2026-07-01',
  reportCadence: 'Relatório ao fim da sprint',
}

export const sprintRoadmap = [
  {
    id: 'SPR-000',
    title: 'Foundation And Operating Model',
    state: 'active',
    goal: 'Fechar workflow, backlog, docs, arquitetura, dados, qualidade e CI/CD baseline.',
    cards: ['OJ-001', 'OJ-002R', 'OJ-003', 'OJ-004', 'OJ-005', 'OJ-006', 'OJ-007', 'OJ-008', 'OJ-009', 'OJ-010', 'OJ-011', 'OJ-012', 'OJ-BE-001', 'OJ-013', 'OJ-014', 'OJ-015', 'OJ-019', 'OJ-020', 'OJ-023', 'OJ-026'],
  },
  {
    id: 'SPR-001',
    title: 'Identity, Access And Project Foundation',
    state: 'planned',
    goal: 'Entregar base de autenticação, RBAC, organizações, projetos, banco inicial e shell autenticado.',
    cards: ['OJ-DB-001', 'OJ-DB-002', 'OJ-DB-003', 'OJ-016', 'OJ-BE-002', 'OJ-AUTH-001', 'OJ-AUTH-002', 'OJ-BE-003', 'OJ-017', 'OJ-FE-001', 'OJ-FE-002', 'OJ-FE-003'],
  },
  {
    id: 'SPR-002',
    title: 'Kanban Board And Issue Movement',
    state: 'planned',
    goal: 'Entregar board Kanban com colunas, cards, movimentação, API de board e UI responsiva.',
    cards: ['OJ-BE-004', 'OJ-018', 'OJ-FE-004', 'OJ-UX-001'],
  },
  {
    id: 'SPR-003',
    title: 'Issues, Comments, Filters And Tests',
    state: 'planned',
    goal: 'Completar fluxo de issue, comentários, filtros, histórico, acessibilidade e suíte E2E MVP.',
    cards: ['OJ-BE-005', 'OJ-FE-005', 'OJ-FE-006', 'OJ-FE-007', 'OJ-021', 'OJ-025'],
  },
  {
    id: 'SPR-004',
    title: 'Release Hardening And Delivery',
    state: 'planned',
    goal: 'Fechar observabilidade, SonarQube, checks obrigatórios, docs automation, deploy, rollback e release readiness.',
    cards: ['OJ-022', 'OJ-024', 'OJ-027', 'OJ-028', 'OJ-029', 'OJ-OBS-001', 'OJ-DOC-001', 'OJ-DOC-002'],
  },
]

const baseSprintCards = [
  {
    id: 'OJ-001',
    title: 'Define product vision',
    owner: 'Mariana Costa',
    role: 'Product Strategy',
    priority: 'P0',
    status: 'done',
  },
  {
    id: 'OJ-002R',
    title: 'Restructure backlog using mandatory card model',
    owner: 'Mariana Costa',
    role: 'Product Strategy',
    priority: 'P0',
    status: 'done',
  },
  {
    id: 'OJ-003',
    title: 'Define autonomous AIA operating model',
    owner: 'Mariana Costa',
    role: 'Product Strategy',
    priority: 'P0',
    status: 'done',
  },
  {
    id: 'OJ-004',
    title: 'Create openjira-docs portal',
    owner: 'Sofia Mendes',
    role: 'Documentation',
    priority: 'P0',
    status: 'done',
  },
  {
    id: 'OJ-005',
    title: 'Publish docs remotely',
    owner: 'Camila Rocha',
    role: 'CI/CD',
    priority: 'P1',
    status: 'blocked',
  },
  {
    id: 'OJ-006',
    title: 'Create sprint report template',
    owner: 'Sofia Mendes',
    role: 'Documentation',
    priority: 'P0',
    status: 'done',
  },
  {
    id: 'OJ-007',
    title: 'Map core user journeys',
    owner: 'Helena Duarte',
    role: 'Requirements',
    priority: 'P0',
    status: 'ready-for-sprint',
  },
  {
    id: 'OJ-008',
    title: 'Define functional requirements by domain',
    owner: 'Helena Duarte',
    role: 'Requirements',
    priority: 'P0',
    status: 'tl-review',
  },
  {
    id: 'OJ-009',
    title: 'Define acceptance criteria for MVP flows',
    owner: 'Renata Barbosa',
    role: 'Quality Analyst',
    priority: 'P0',
    status: 'tl-review',
  },
  {
    id: 'OJ-010',
    title: 'Define technical architecture',
    owner: 'Rafael Almeida',
    role: 'Tech Lead',
    priority: 'P0',
    status: 'tl-review',
  },
  {
    id: 'OJ-011',
    title: 'Choose ORM and migration strategy',
    owner: 'Rafael Almeida',
    role: 'Tech Lead',
    priority: 'P0',
    status: 'tl-review',
  },
  {
    id: 'OJ-012',
    title: 'Define auth and RBAC strategy',
    owner: 'Gabriel Martins',
    role: 'Backend',
    priority: 'P0',
    status: 'tl-review',
  },
  {
    id: 'OJ-013',
    title: 'Design initial PostgreSQL model',
    owner: 'Eduardo Ribeiro',
    role: 'DBA PostgreSQL',
    priority: 'P0',
    status: 'tl-review',
  },
  {
    id: 'OJ-014',
    title: 'Define local database strategy',
    owner: 'Eduardo Ribeiro',
    role: 'DBA PostgreSQL',
    priority: 'P0',
    status: 'tl-review',
  },
  {
    id: 'OJ-015',
    title: 'Scaffold openjira-server',
    owner: 'Gabriel Martins',
    role: 'Backend NestJS',
    priority: 'P0',
    status: 'tl-review',
  },
  {
    id: 'OJ-BE-001',
    title: 'Define REST API contract for MVP',
    owner: 'Gabriel Martins',
    role: 'Backend',
    priority: 'P0',
    status: 'tl-review',
  },
  {
    id: 'OJ-019',
    title: 'Define quality gates',
    owner: 'Renata Barbosa',
    role: 'Quality Gate/QA',
    priority: 'P0',
    status: 'tl-review',
  },
  {
    id: 'OJ-020',
    title: 'Define CI/CD baseline',
    owner: 'Camila Rocha',
    role: 'CI/CD',
    priority: 'P0',
    status: 'tl-review',
  },
  {
    id: 'OJ-023',
    title: 'Define test pyramid and coverage policy',
    owner: 'Bruno Teixeira',
    role: 'Test Engineering',
    priority: 'P0',
    status: 'tl-review',
  },
  {
    id: 'OJ-026',
    title: 'Create evidence templates',
    owner: 'Sofia Mendes',
    role: 'Documentation',
    priority: 'P0',
    status: 'ready-for-sprint',
  },
]

const sharedDoneExpectations = {
  testExpectations: ['Validar consistência do documento fonte e links referenciados.'],
  qaExpectations: ['Confirmar que o artefato atende ao workflow AIA e não deixa campo obrigatório em aberto.'],
  documentationExpectations: ['Manter Markdown versionado e rastreável no portal.'],
}

const cardDetails = {
  'OJ-001': {
    assignee: 'Mariana Costa',
    tags: ['Produto', 'Visão', 'MVP'],
    dependencies: [],
    evidence: ['docs/product/mvp-backlog.md'],
    description: 'Define a visão de produto e o recorte de MVP usado pela AIA.',
    acceptanceCriteria: ['Visão do produto registrada.', 'Escopo do MVP descrito.', 'Documento publicado no portal.'],
    nextAction: 'Manter como referência para priorização das próximas sprints.',
    sourcePath: 'docs/product/mvp-backlog.md',
    ...sharedDoneExpectations,
  },
  'OJ-002R': {
    assignee: 'Mariana Costa',
    tags: ['Backlog', 'Card model', 'Governança'],
    dependencies: ['OJ-001'],
    evidence: ['docs/product/mvp-backlog.md'],
    description: 'Reestrutura o backlog usando o card model obrigatório da AIA.',
    acceptanceCriteria: ['Cards possuem dono, prioridade, dependências e critérios.', 'Backlog está versionado.', 'Cards futuros permanecem fora da execução até aprovação.'],
    nextAction: 'Usar backlog como fonte principal para planejamento da SPR-000.',
    sourcePath: 'docs/product/mvp-backlog.md',
    ...sharedDoneExpectations,
  },
  'OJ-003': {
    assignee: 'Mariana Costa',
    tags: ['AIA', 'Workflow', 'Operação'],
    dependencies: ['OJ-001'],
    evidence: ['docs/operations/aia-delivery-workflow.md'],
    description: 'Define o modelo operacional autônomo da squad AIA.',
    acceptanceCriteria: ['Papéis descritos.', 'Fluxo de retorno e priorização registrado.', 'Limites de atuação por função definidos.'],
    nextAction: 'Aplicar o fluxo em todo card novo ou retornado por QA, tester ou TechLead.',
    sourcePath: 'docs/operations/aia-delivery-workflow.md',
    ...sharedDoneExpectations,
  },
  'OJ-004': {
    assignee: 'Sofia Mendes',
    tags: ['Portal', 'Documentação', 'Vite'],
    dependencies: ['OJ-001', 'OJ-003'],
    evidence: ['src/main.js', 'src/content.js', 'src/styles.scss'],
    description: 'Cria o portal estático OpenJira Docs para acompanhar produto, sprints e governança.',
    acceptanceCriteria: ['Portal executa localmente.', 'Conteúdo operacional é renderizado.', 'Build Vite passa sem erro.'],
    nextAction: 'Evoluir para Manager View após validação de UX e TechLead.',
    sourcePath: 'src/main.js',
    ...sharedDoneExpectations,
  },
  'OJ-005': {
    assignee: 'Camila Rocha',
    tags: ['CI/CD', 'Deploy', 'Bloqueio'],
    dependencies: ['Repositório GitHub dedicado', 'Decisão de nome do produto'],
    evidence: [],
    description: 'Publica o portal remoto em um host estático para consulta na rede ou pela internet.',
    acceptanceCriteria: ['Repositório remoto definido.', 'Pipeline de build configurado.', 'URL de preview ou produção registrada.'],
    testExpectations: ['Validar build em CI e acesso ao artefato publicado.'],
    qaExpectations: ['Confirmar que a URL entrega a versão correta e que o conteúdo sensível não foi exposto indevidamente.'],
    documentationExpectations: ['Registrar URL, estratégia de deploy e fallback operacional.'],
    nextAction: 'Aguardar confirmação do nome do repositório antes de criar remoto e pipeline.',
    sourcePath: 'docs/product/mvp-backlog.md',
  },
  'OJ-006': {
    assignee: 'Sofia Mendes',
    tags: ['Sprint', 'Relatório', 'Documentação'],
    dependencies: ['OJ-003'],
    evidence: ['docs/sprints/report-template.md'],
    description: 'Cria o template de relatório final de sprint.',
    acceptanceCriteria: ['Template possui entregas, riscos, métricas, pendências e decisão recomendada.', 'Formato pode ser reutilizado por sprint.'],
    nextAction: 'Usar o template no encerramento da SPR-000.',
    sourcePath: 'docs/sprints/report-template.md',
    ...sharedDoneExpectations,
  },
  'OJ-007': {
    assignee: 'Helena Duarte',
    tags: ['Requisitos', 'Jornadas', 'Ready'],
    dependencies: [],
    evidence: ['docs/requirements/core-user-journeys.md'],
    description: 'Mapeia as jornadas centrais do usuário para orientar requisitos, aceitação e testes.',
    acceptanceCriteria: ['Jornadas de autenticação, organização, projeto, board e issue estão descritas.', 'Atores e resultados esperados estão claros.', 'Artefato está pronto para alimentar OJ-008 e OJ-009.'],
    testExpectations: ['Transformar jornadas críticas em cenários de aceitação e E2E quando a UI existir.'],
    qaExpectations: ['Validar cobertura das jornadas essenciais do MVP.'],
    documentationExpectations: ['Manter o documento de jornadas como evidência primária.'],
    nextAction: 'Planejar na sprint e usar como entrada para OJ-008.',
    sourcePath: 'docs/requirements/core-user-journeys.md',
  },
  'OJ-008': {
    assignee: 'Helena Duarte',
    tags: ['Requisitos', 'Domínios', 'TL Review'],
    dependencies: ['OJ-007'],
    evidence: ['docs/product/mvp-backlog.md'],
    description: 'Define requisitos funcionais por domínio do MVP.',
    acceptanceCriteria: ['Domínios do MVP têm requisitos rastreáveis.', 'Requisitos citam jornadas relevantes.', 'Lacunas são marcadas para TechLead.'],
    testExpectations: ['Permitir derivar critérios de aceitação por fluxo.'],
    qaExpectations: ['Revisar ambiguidade, completude e dependências.'],
    documentationExpectations: ['Atualizar backlog e docs de requisitos.'],
    nextAction: 'Rafael deve revisar após aceitação de OJ-007.',
    sourcePath: 'docs/product/mvp-backlog.md',
  },
  'OJ-009': {
    assignee: 'Renata Barbosa',
    tags: ['QA', 'Aceitação', 'MVP'],
    dependencies: ['OJ-007', 'OJ-008'],
    evidence: ['docs/product/mvp-backlog.md'],
    description: 'Define critérios de aceitação para os fluxos MVP.',
    acceptanceCriteria: ['Critérios cobrem happy path e falhas principais.', 'Critérios são objetivos e testáveis.', 'Cada fluxo crítico tem resultado esperado.'],
    testExpectations: ['Gerar base para testes de integração e E2E.'],
    qaExpectations: ['Bloquear critérios subjetivos ou sem evidência verificável.'],
    documentationExpectations: ['Publicar critérios no backlog e documentos de qualidade.'],
    nextAction: 'Aguardar requisitos por domínio e revisar com Rafael.',
    sourcePath: 'docs/product/mvp-backlog.md',
  },
  'OJ-010': {
    assignee: 'Rafael Almeida',
    tags: ['Arquitetura', 'Tech Lead', 'Decisão'],
    dependencies: ['OJ-008'],
    evidence: [],
    description: 'Define a arquitetura técnica base do OpenJira.',
    acceptanceCriteria: ['Frontend, backend, banco, autenticação e deploy têm direção técnica.', 'Riscos e decisões estão registrados.', 'Dependências para CI/CD são explícitas.'],
    testExpectations: ['Indicar impactos em testes unitários, integração e E2E.'],
    qaExpectations: ['Verificar rastreabilidade entre arquitetura, requisitos e qualidade.'],
    documentationExpectations: ['Registrar decisões arquiteturais em Markdown.'],
    nextAction: 'Rafael deve consolidar decisão antes de liberar CI/CD e implementação ampla.',
    sourcePath: 'docs/product/mvp-backlog.md',
  },
  'OJ-011': {
    assignee: 'Rafael Almeida',
    tags: ['ORM', 'Migrations', 'Banco'],
    dependencies: ['OJ-010'],
    evidence: ['docs/product/mvp-backlog.md'],
    description: 'Escolhe ORM e estratégia de migração para o backend NestJS.',
    acceptanceCriteria: ['ORM selecionado.', 'Estratégia de migration e rollback definida.', 'Integração com PostgreSQL documentada.'],
    testExpectations: ['Prever testes de migration e fixtures.'],
    qaExpectations: ['Validar que a escolha suporta auditoria, CI e ambientes locais.'],
    documentationExpectations: ['Registrar decisão e comandos principais.'],
    nextAction: 'Aguardar arquitetura técnica.',
    sourcePath: 'docs/product/mvp-backlog.md',
  },
  'OJ-012': {
    assignee: 'Gabriel Martins',
    tags: ['Auth', 'RBAC', 'Backend'],
    dependencies: ['OJ-008', 'OJ-010'],
    evidence: ['docs/product/mvp-backlog.md'],
    description: 'Define estratégia de autenticação e autorização por papéis.',
    acceptanceCriteria: ['Fluxo de login e sessão definido.', 'Papéis e permissões MVP descritos.', 'Riscos de segurança registrados.'],
    testExpectations: ['Definir cenários de permissão negada, expiração e acesso permitido.'],
    qaExpectations: ['Validar coerência com jornadas e requisitos.'],
    documentationExpectations: ['Atualizar docs de backend e requisitos.'],
    nextAction: 'Rafael deve revisar após arquitetura base.',
    sourcePath: 'docs/product/mvp-backlog.md',
  },
  'OJ-013': {
    assignee: 'Eduardo Ribeiro',
    tags: ['PostgreSQL', 'Modelo de dados', 'DBA'],
    dependencies: ['OJ-011', 'OJ-012'],
    evidence: ['docs/product/mvp-backlog.md'],
    description: 'Desenha o modelo PostgreSQL inicial para organizações, projetos, issues e usuários.',
    acceptanceCriteria: ['Entidades principais descritas.', 'Relacionamentos e chaves identificados.', 'Restrições e índices candidatos registrados.'],
    testExpectations: ['Prever fixtures e validações de integridade.'],
    qaExpectations: ['Verificar suporte aos fluxos MVP e histórico básico.'],
    documentationExpectations: ['Adicionar diagrama ou tabela de modelo de dados.'],
    nextAction: 'Revisar com Rafael depois da estratégia de ORM e RBAC.',
    sourcePath: 'docs/product/mvp-backlog.md',
  },
  'OJ-014': {
    assignee: 'Eduardo Ribeiro',
    tags: ['Banco local', 'Docker', 'PostgreSQL'],
    dependencies: ['OJ-013'],
    evidence: ['docs/product/mvp-backlog.md'],
    description: 'Define estratégia de banco local para desenvolvimento e testes.',
    acceptanceCriteria: ['Ambiente local é reproduzível.', 'Seeds e reset são previstos.', 'Dependências de CI/CD estão claras.'],
    testExpectations: ['Suportar execução automatizada de testes com banco limpo.'],
    qaExpectations: ['Confirmar que a estratégia evita estado compartilhado entre testes.'],
    documentationExpectations: ['Documentar comandos de setup, reset e troubleshooting.'],
    nextAction: 'Aguardar modelo inicial e alinhar com CI/CD.',
    sourcePath: 'docs/product/mvp-backlog.md',
  },
  'OJ-015': {
    assignee: 'Gabriel Martins',
    tags: ['NestJS', 'Scaffold', 'Backend'],
    dependencies: ['OJ-010'],
    evidence: ['docs/product/mvp-backlog.md'],
    description: 'Cria o scaffold do backend NestJS.',
    acceptanceCriteria: ['Projeto backend inicial criado.', 'Scripts principais definidos.', 'Build e lint mínimos executam.'],
    testExpectations: ['Adicionar teste inicial de saúde do projeto.'],
    qaExpectations: ['Validar que o scaffold segue decisões técnicas aprovadas.'],
    documentationExpectations: ['Registrar comandos de desenvolvimento no README do backend.'],
    nextAction: 'Não iniciar até arquitetura técnica estar aprovada.',
    sourcePath: 'docs/product/mvp-backlog.md',
  },
  'OJ-BE-001': {
    assignee: 'Gabriel Martins',
    tags: ['API', 'Contrato', 'Backend'],
    dependencies: ['OJ-007', 'OJ-008', 'OJ-010', 'OJ-013'],
    evidence: ['docs/product/mvp-backlog.md'],
    description: 'Define o contrato REST inicial para o MVP.',
    acceptanceCriteria: ['Endpoints principais mapeados.', 'Payloads e erros documentados.', 'Contrato cobre jornadas MVP.'],
    testExpectations: ['Basear testes de integração no contrato aprovado.'],
    qaExpectations: ['Validar consistência entre contrato, critérios de aceitação e requisitos.'],
    documentationExpectations: ['Publicar contrato em Markdown ou OpenAPI quando definido.'],
    nextAction: 'Aguardar requisitos e critérios de aceitação.',
    sourcePath: 'docs/product/mvp-backlog.md',
  },
  'OJ-017': {
    assignee: 'Lucas Ferreira',
    tags: ['Frontend', 'Next.js', 'Navegação'],
    dependencies: ['OJ-008', 'OJ-010', 'OJ-018'],
    evidence: ['docs/product/mvp-backlog.md'],
    description: 'Define app shell e navegação do frontend Next.js.',
    acceptanceCriteria: ['Estrutura de navegação aprovada.', 'Rotas principais do MVP mapeadas.', 'Estados de loading, vazio e erro previstos.'],
    testExpectations: ['Prever cobertura de navegação e renderização principal.'],
    qaExpectations: ['Validar acessibilidade e clareza dos fluxos.'],
    documentationExpectations: ['Registrar decisões de shell e navegação.'],
    nextAction: 'Aguardar UX/UI MVP e arquitetura técnica.',
    sourcePath: 'docs/product/mvp-backlog.md',
  },
  'OJ-018': {
    assignee: 'Beatriz Nogueira',
    tags: ['UX/UI', 'Board', 'MVP'],
    dependencies: ['OJ-007', 'OJ-008'],
    evidence: ['docs/design/openjira-manager-view-ui-report.md'],
    description: 'Define telas MVP e regras de UX/UI do board.',
    acceptanceCriteria: ['Telas principais descritas.', 'Regras de board e interação registradas.', 'Fluxos móveis e desktop considerados.'],
    testExpectations: ['Definir expectativas de acessibilidade e estados visuais.'],
    qaExpectations: ['Rafael valida se proposta é implementável e alinhada ao MVP.'],
    documentationExpectations: ['Manter relatório de UX com wireframes e Mermaid.'],
    nextAction: 'Usar relatório como contrato para implementação visual do portal.',
    sourcePath: 'docs/design/openjira-manager-view-ui-report.md',
  },
  'OJ-019': {
    assignee: 'Renata Barbosa',
    tags: ['Quality Gate', 'QA', 'Política'],
    dependencies: ['OJ-009'],
    evidence: ['docs/quality/test-policy.md'],
    description: 'Define quality gates mínimos para aceitar entregas da AIA.',
    acceptanceCriteria: ['Gates mínimos são objetivos.', 'Falhas bloqueantes estão claras.', 'Responsabilidades de QA, tester e TechLead são explícitas.'],
    testExpectations: ['Amarrar lint, build, testes e evidências aos gates.'],
    qaExpectations: ['Garantir que nenhum card avance sem evidência suficiente.'],
    documentationExpectations: ['Atualizar política de qualidade.'],
    nextAction: 'Concluir revisão para destravar OJ-023 e OJ-020.',
    sourcePath: 'docs/quality/test-policy.md',
  },
  'OJ-020': {
    assignee: 'Camila Rocha',
    tags: ['CI/CD', 'Pipeline', 'Baseline'],
    dependencies: ['OJ-010', 'OJ-014', 'OJ-019', 'OJ-023'],
    evidence: ['docs/product/mvp-backlog.md'],
    description: 'Define baseline de CI/CD para build, testes e publicação.',
    acceptanceCriteria: ['Pipeline mínimo descrito.', 'Checks obrigatórios mapeados.', 'Estratégia de artefatos e evidências definida.'],
    testExpectations: ['Pipeline deve executar validações automáticas exigidas pelos gates.'],
    qaExpectations: ['QA confirma que falhas impedem avanço indevido.'],
    documentationExpectations: ['Registrar jobs, variáveis, ambientes e evidências.'],
    nextAction: 'Aguardar arquitetura, banco local, quality gates e política de testes.',
    sourcePath: 'docs/product/mvp-backlog.md',
  },
  'OJ-023': {
    assignee: 'Bruno Teixeira',
    tags: ['Testes', 'Cobertura', 'Política'],
    dependencies: ['OJ-009', 'OJ-019'],
    evidence: ['docs/quality/test-policy.md'],
    description: 'Define pirâmide de testes e política de cobertura.',
    acceptanceCriteria: ['Camadas de teste estão definidas.', 'Cobertura mínima por tipo de mudança está clara.', 'Política não depende da estratégia executável de E2E futura.'],
    testExpectations: ['Servir como base para estratégia de integração e E2E em OJ-021.'],
    qaExpectations: ['Validar que a política é aplicável já na fundação.'],
    documentationExpectations: ['Atualizar docs de qualidade e backlog.'],
    nextAction: 'Rafael deve revisar após OJ-019.',
    sourcePath: 'docs/quality/test-policy.md',
  },
  'OJ-026': {
    assignee: 'Sofia Mendes',
    tags: ['Evidências', 'Templates', 'Ready'],
    dependencies: [],
    evidence: ['docs/evidence/index.md', 'docs/evidence/qa-gate.md', 'docs/evidence/release-evidence.md'],
    description: 'Cria templates de evidência para sucesso, falha, QA, SonarQube, deploy e release.',
    acceptanceCriteria: ['Templates existem para cenários principais.', 'Campos obrigatórios estão claros.', 'Evidências são reutilizáveis por sprint.'],
    testExpectations: ['Tester consegue registrar sucesso e falha com passos reproduzíveis.'],
    qaExpectations: ['QA consegue aprovar ou reprovar usando o template.'],
    documentationExpectations: ['Indexar todos os templates em docs/evidence/index.md.'],
    nextAction: 'Planejar na sprint e exigir uso nos próximos retornos de QA/tester.',
    sourcePath: 'docs/evidence/index.md',
  },
}

export const sprintCards = baseSprintCards.map((card) => ({
  assignee: card.owner,
  tags: [],
  dependencies: [],
  evidence: [],
  description: '',
  acceptanceCriteria: [],
  testExpectations: [],
  qaExpectations: [],
  documentationExpectations: [],
  nextAction: '',
  sourcePath: 'docs/product/mvp-backlog.md',
  ...card,
  ...cardDetails[card.id],
}))

export const workflowColumns = [
  { id: 'ready-for-sprint', title: 'Ready for Sprint', empty: 'Nenhum card pronto para sprint.' },
  { id: 'tl-review', title: 'TL Review', empty: 'Nenhum card aguardando TechLead.' },
  { id: 'planned', title: 'Planejado', empty: 'Nenhum card planejado.' },
  { id: 'in-development', title: 'Em desenvolvimento', empty: 'Nenhum card em desenvolvimento.' },
  { id: 'blocked', title: 'Bloqueado', empty: 'Nenhum bloqueio registrado.' },
  { id: 'done', title: 'Concluído', empty: 'Nada concluído ainda.' },
]
